import pygame

# Constants

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

HIGHER = 'higher'
LOWER = 'lower'
PLAYER1 = 'Player 1'
PLAYER2 = 'Player 2'
PLAYER3 = 'Player 3'
PLAYER4 = 'Player 4'
PLAYER5 = 'Player 5'
DEALER = 'Dealer'

# Window
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
WINDOW_CENTER_X = WINDOW_WIDTH / 2
WINDOW_CENTER_Y = WINDOW_HEIGHT / 2

# Player locations
DEALER_LEFT = 460
PLAYER_LEFT_LIST = [127, 293, 460, 627, 793, DEALER_LEFT]
PLAYER_LIST = [PLAYER1, PLAYER2, PLAYER3, PLAYER4, PLAYER5, DEALER]

# Card spacing
BACK_OF_CARD_IMAGE = pygame.image.load('images/BackOfCard.png')
CARD_WIDTH = BACK_OF_CARD_IMAGE.get_width()
CARD_HEIGHT = BACK_OF_CARD_IMAGE.get_height()
CARD_OFFSET_X = -30
CARD_OFFSET_Y = -30

# Fonts
SCORE_FONT_SIZE = 30